[project]
name = "ConcertBot"
version = "0.1.0"
description = "A python HTTP interactive robot that complies with the OneBot protocol"
readme = "README.md"
requires-python = ">=3.12,<4.0"
authors = [
    { name = "shadlc", email = "i@shadlc.net" }
]
dependencies = [
    "pillow>=11.2.1,<12",
    "colorama>=0.4.6,<0.5",
    "idna>=3.10,<4",
    "certifi>=2025.8.3,<2026",
    "httpx>=0.28.1,<0.29",
]

[tool.uv]
package = false


[tool.pylint.basic]
module-rgx = "^([a-z_][a-z0-9_]*|[0-9]{3}[a-z][a-z0-9_]*)$"

[tool.pylint.format]
max-line-length = 200
